import { useEffect, useState } from 'react';
import { Box, Grid, LinearProgress, Rating, Stack, Typography } from '@mui/material';
import AppCard from '../components/AppCard'; import ErrorState from '../components/ErrorState'; import LoadingState from '../components/LoadingState'; import { MetricCard, PageHeading } from './DashboardComponents';
import { getChiefFeedback, getFeedbackAnalytics } from '../services/chiefService';
function ChiefFeedbackPage() {
  const [analytics, setAnalytics] = useState(null); const [feedback, setFeedback] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([getFeedbackAnalytics(), getChiefFeedback()]).then(([a, f]) => { setAnalytics(a); setFeedback(f.feedback); }).catch((e) => setError(e.response?.data?.message || 'Unable to load feedback analytics.')); }, []);
  if (!analytics && !error) return <LoadingState message="Loading feedback insights…" />;
  if (error) return <ErrorState message={error} />;
  return <><PageHeading title="Feedback & ratings" subtitle="Use student and staff feedback to continuously improve your meal menu." /><Grid container spacing={2.5}><Grid size={{ xs: 12, sm: 6 }}><MetricCard title="Average food rating" value={`${Number(analytics.summary.averageRating).toFixed(1)} / 5`} note="Across all submitted meal ratings" /></Grid><Grid size={{ xs: 12, sm: 6 }}><MetricCard title="Total responses" value={analytics.summary.totalRatings} note="Student and staff feedback submissions" color="#e53935" /></Grid><Grid size={{ xs: 12, lg: 7 }}><AppCard><Typography variant="h6" fontWeight={800}>Meal rating chart</Typography><Typography variant="body2" color="text.secondary" mb={2.5}>Average ratings by meal. Low scores highlight items to review.</Typography><Stack spacing={2.25}>{analytics.ratings.length ? analytics.ratings.map((item) => <Box key={item._id}><Stack direction="row" justifyContent="space-between" alignItems="center" mb={.5}><Box><Typography fontWeight={750}>{item.foodName}</Typography><Typography variant="caption" color="text.secondary" textTransform="capitalize">{item.mealType} · {item.ratingCount} rating{item.ratingCount === 1 ? '' : 's'}</Typography></Box><Stack direction="row" spacing={.5} alignItems="center"><Rating value={item.averageRating} precision={0.1} readOnly size="small" /><Typography fontWeight={800}>{item.averageRating.toFixed(1)}</Typography></Stack></Stack><LinearProgress variant="determinate" value={item.averageRating * 20} color={item.averageRating < 3 ? 'error' : item.averageRating < 4 ? 'warning' : 'primary'} sx={{ height: 10, borderRadius: 8, bgcolor: '#fff0ea' }} /></Box>) : <Typography color="text.secondary">No ratings have been submitted yet.</Typography>}</Stack></AppCard></Grid><Grid size={{ xs: 12, lg: 5 }}><AppCard><Typography variant="h6" fontWeight={800} mb={2}>Recent student and staff comments</Typography><Stack spacing={2}>{feedback.length ? feedback.map((item) => <Box key={item._id} sx={{ pb: 1.5, borderBottom: '1px solid #fff0ea' }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={750}>{item.mealId?.foodName || 'Meal feedback'}</Typography><Rating value={item.rating} readOnly size="small" /></Stack><Typography variant="body2" color="text.secondary" mt={.5}>{item.comment || 'No comment provided.'}</Typography><Typography variant="caption" color="text.secondary">{item.studentId?.name || 'Student / Staff'} · {new Date(item.createdAt).toLocaleDateString()}</Typography></Box>) : <Typography color="text.secondary">No feedback is available yet.</Typography>}</Stack></AppCard></Grid></Grid></>;
}
export default ChiefFeedbackPage;
