import { useEffect, useState } from 'react';
import { Alert, Box, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import AppButton from '../components/AppButton'; import AppCard from '../components/AppCard'; import ErrorState from '../components/ErrorState'; import LoadingState from '../components/LoadingState'; import { MetricCard, PageHeading } from './DashboardComponents'; import { getInventoryDashboard, recordIngredientUsage } from '../services/chiefService';
function InventoryDashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [usage, setUsage] = useState({ itemId: '', quantity: '', note: '' });
  const load = async () => { try { setData(await getInventoryDashboard()); } catch (e) { setError(e.response?.data?.message || 'Unable to load inventory dashboard.'); } };
  useEffect(() => { load(); }, []);
  const saveUsage = async (event) => { event.preventDefault(); setError(''); setNotice(''); try { await recordIngredientUsage(usage.itemId, { quantity: Number(usage.quantity), note: usage.note }); setUsage({ itemId: '', quantity: '', note: '' }); setNotice('Ingredient usage recorded and stock updated.'); load(); } catch (e) { setError(e.response?.data?.message || 'Unable to record ingredient usage.'); } };
  if (!data && !error) return <LoadingState message="Loading inventory dashboard…" />;
  if (error && !data) return <ErrorState message={error} />;
  return <><PageHeading title="Inventory dashboard" subtitle="Monitor ingredient stock, low-stock alerts, and kitchen usage." />{error && <Box mb={2}><ErrorState message={error} /></Box>}{notice && <Alert severity="success" sx={{ mb: 2 }}>{notice}</Alert>}<Grid container spacing={2.5}><Grid size={{ xs: 12, sm: 6 }}><MetricCard title="Tracked ingredients" value={data.totalItems} note="Items in current inventory" /></Grid><Grid size={{ xs: 12, sm: 6 }}><MetricCard title="Low-stock alerts" value={data.lowStockCount} note="Items at or below their threshold" color="#e53935" /></Grid><Grid size={{ xs: 12, lg: 5 }}><AppCard><Typography variant="h6" fontWeight={800} mb={2}>Record ingredient usage</Typography><Stack component="form" onSubmit={saveUsage} spacing={2}><TextField select label="Ingredient" value={usage.itemId} onChange={(e) => setUsage({ ...usage, itemId: e.target.value })} required><MenuItem value="" disabled>Select ingredient</MenuItem>{data.items.map((item) => <MenuItem key={item._id} value={item._id}>{item.itemName} ({item.quantity} {item.unit})</MenuItem>)}</TextField><TextField label="Quantity used" type="number" value={usage.quantity} onChange={(e) => setUsage({ ...usage, quantity: e.target.value })} inputProps={{ min: .001, step: 'any' }} required /><TextField label="Usage note (optional)" value={usage.note} onChange={(e) => setUsage({ ...usage, note: e.target.value })} /><AppButton type="submit" disabled={!usage.itemId}>Record usage</AppButton></Stack></AppCard></Grid><Grid size={{ xs: 12, lg: 7 }}><AppCard><Typography variant="h6" fontWeight={800} mb={2}>Low-stock alerts</Typography><Stack spacing={1.5}>{data.lowStockItems.length ? data.lowStockItems.map((item) => <Box key={item._id} sx={{ p: 1.5, bgcolor: '#fff1f0', borderRadius: 2 }}><Typography fontWeight={750}>{item.itemName}</Typography><Typography variant="body2" color="error.main">{item.quantity} {item.unit} remaining · alert threshold {item.lowStockThreshold} {item.unit}</Typography></Box>) : <Typography color="text.secondary">All inventory levels are above their alert thresholds.</Typography>}</Stack></AppCard></Grid><Grid size={{ xs: 12 }}><AppCard><Typography variant="h6" fontWeight={800} mb={2}>Recent ingredient usage</Typography><Stack spacing={1}>{data.recentUsage.length ? data.recentUsage.map((entry) => <Box key={entry._id} sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, p: 1.25, borderBottom: '1px solid #fff0ea' }}><Box><Typography fontWeight={700}>{entry.itemName}</Typography><Typography variant="caption" color="text.secondary">{entry.note || 'Kitchen usage'} · {entry.usedBy?.name || 'Mess Chief'}</Typography></Box><Typography color="text.secondary">−{entry.quantity} {entry.unit}<br /><Typography component="span" variant="caption">{new Date(entry.usedAt).toLocaleString()}</Typography></Typography></Box>) : <Typography color="text.secondary">No ingredient usage recorded yet.</Typography>}</Stack></AppCard></Grid></Grid></>;
}
export default InventoryDashboardPage;
