import { useEffect, useMemo, useState } from 'react';
import { Box, Checkbox, Chip, FormControlLabel, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import AppButton from '../components/AppButton';
import AppCard from '../components/AppCard';
import AppTable from '../components/AppTable';
import ErrorState from '../components/ErrorState';
import LoadingState from '../components/LoadingState';
import { PageHeading } from './DashboardComponents';
import { createMealOptions, deleteMeal, getChiefMenu, getMenuHistory, updateMeal } from '../services/chiefService';

const emptyForm = { mealType: 'lunch', foodCategory: 'veg', foodName: '', vegFoodName: '', nonVegFoodName: '', date: '', openingTime: '08:00', closingTime: '10:00', price: '', originalCost: '', messPaymentAmount: 0, vegOriginalCost: '', nonVegOriginalCost: '', isAvailable: true, ingredients: [] };
const pad = (value) => String(value).padStart(2, '0');
const dateKey = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; };
const timeValue = (value, fallback) => typeof value === 'string' && /^\d{2}:\d{2}/.test(value) ? value.slice(0, 5) : fallback;
const categoryLabel = (meal) => meal.foodCategory === 'non_veg' ? 'Non-Veg' : 'Veg';

function MenuManagementPage() {
  const [meals, setMeals] = useState([]); const [history, setHistory] = useState([]); const [historyDate, setHistoryDate] = useState('');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [deleting, setDeleting] = useState(false); const [selectedHistoryIds, setSelectedHistoryIds] = useState([]); const [editingId, setEditingId] = useState(null); const [form, setForm] = useState(emptyForm);
  const load = async () => { setLoading(true); try { const [weekly, all] = await Promise.all([getChiefMenu(), getMenuHistory()]); setMeals(weekly.meals); setHistory(all.meals); } catch (e) { setError(e.response?.data?.message || 'Unable to load menu.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setError(''); const price = Number(form.price); if (!Number.isFinite(price) || price < 0) return setError('Meal price must be 0 or more.'); if (!form.openingTime || !form.closingTime || form.openingTime >= form.closingTime) return setError('Closing time must be after opening time.'); try { const payload = { ...form, vegFoodName: form.foodName, price }; if (editingId) await updateMeal(editingId, payload); else await createMealOptions(payload); setEditingId(null); setForm(emptyForm); load(); } catch (e) { setError(e.response?.data?.message || 'Unable to save meal options.'); } };
  const edit = (meal) => { setEditingId(meal._id); setForm({ ...emptyForm, mealType: meal.mealType, foodCategory: meal.foodCategory || 'veg', foodName: meal.foodName, date: dateKey(meal.date), openingTime: timeValue(meal.openingTime, '08:00'), closingTime: timeValue(meal.closingTime, '10:00'), price: meal.price || 0, originalCost: meal.originalCost || 0, messPaymentAmount: meal.messPaymentAmount || 0, isAvailable: meal.isAvailable, ingredients: meal.ingredients || [] }); };
  const remove = async (id) => { try { await deleteMeal(id); load(); } catch (e) { setError(e.response?.data?.message || 'Unable to delete meal.'); } };
  const visibleHistory = useMemo(() => history.filter((meal) => !historyDate || dateKey(meal.date) === historyDate), [history, historyDate]);
  const today = dateKey(new Date());
  const pastHistory = useMemo(() => visibleHistory.filter((meal) => dateKey(meal.date) < today), [visibleHistory, today]);
  const toggleHistory = (id) => setSelectedHistoryIds((selected) => selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]);
  const deleteSelected = async () => {
    const selected = selectedHistoryIds.filter((id) => pastHistory.some((meal) => meal._id === id));
    if (!selected.length || !window.confirm(`Delete ${selected.length} selected past record${selected.length === 1 ? '' : 's'}? This action cannot be undone.`)) return;
    setDeleting(true); setError('');
    try { await Promise.all(selected.map(deleteMeal)); setSelectedHistoryIds([]); await load(); }
    catch (e) { setError(e.response?.data?.message || 'Unable to delete the selected records.'); }
    finally { setDeleting(false); }
  };
  if (loading) return <LoadingState message="Loading menu…" />;
  return <><PageHeading title="Menu management" subtitle="Create Veg and Non-Veg choices; each student can select one option per meal." />{error && <Box mb={2}><ErrorState message={error} /></Box>}<Grid container spacing={2.5}>
    <Grid size={{ xs: 12, lg: 4 }}><AppCard><Typography variant="h6" fontWeight={800} mb={2}>{editingId ? 'Edit meal' : 'Add meal'}</Typography><Stack component="form" onSubmit={submit} spacing={2}>
      <TextField select name="mealType" label="Meal type" value={form.mealType} onChange={change}>{['breakfast', 'lunch', 'dinner', 'snack'].map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField>
      {editingId ? <TextField select name="foodCategory" label="Food category" value={form.foodCategory} onChange={change}><MenuItem value="veg">Veg</MenuItem><MenuItem value="non_veg">Non-Veg</MenuItem></TextField> : <TextField name="nonVegFoodName" label="Non-Veg food name" value={form.nonVegFoodName} onChange={change} required />}
      {editingId ? <TextField name="originalCost" label="Original cost per food" type="number" value={form.originalCost} onChange={change} required slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /> : <><TextField name="vegOriginalCost" label="Veg original cost per food" type="number" value={form.vegOriginalCost} onChange={change} required slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /><TextField name="nonVegOriginalCost" label="Non-Veg original cost per food" type="number" value={form.nonVegOriginalCost} onChange={change} required slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /></>}
      <TextField name="foodName" label="Food name" value={form.foodName} onChange={change} required /><TextField name="date" label="Meal date" type="date" value={form.date} onChange={change} required slotProps={{ inputLabel: { shrink: true } }} /><TextField name="openingTime" label="Opening Time" type="time" value={form.openingTime} onChange={change} required slotProps={{ inputLabel: { shrink: true } }} /><TextField name="closingTime" label="Closing Time" type="time" value={form.closingTime} onChange={change} required slotProps={{ inputLabel: { shrink: true } }} /><TextField name="price" label="Price per meal" type="number" value={form.price} onChange={change} required slotProps={{ htmlInput: { min: 0, step: '0.01' } }} /><FormControlLabel control={<Checkbox checked={form.isAvailable} onChange={(event) => setForm({ ...form, isAvailable: event.target.checked })} />} label="Meal available for booking" /><Stack direction="row" spacing={1}><AppButton type="submit">{editingId ? 'Save changes' : 'Add to menu'}</AppButton>{editingId && <AppButton type="button" color="inherit" onClick={() => { setEditingId(null); setForm(emptyForm); }}>Cancel</AppButton>}</Stack>
    </Stack></AppCard></Grid>
    <Grid size={{ xs: 12, lg: 8 }}><Grid container spacing={2}>{meals.map((meal) => <Grid key={meal._id} size={{ xs: 12, md: 6 }}><AppCard><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800} textTransform="capitalize">{meal.mealType} · {meal.foodName}</Typography><Chip size="small" label={categoryLabel(meal)} color={meal.foodCategory === 'non_veg' ? 'error' : 'success'} /></Stack><Typography variant="body2" color="text.secondary" mt={1}>{new Date(meal.date).toLocaleDateString()} · {meal.quantity} confirmed · Rs. {Number(meal.price || 0).toFixed(2)}</Typography><Typography variant="caption" color={meal.isAvailable ? 'success.main' : 'error.main'} display="block" mt={1}>{meal.isAvailable ? 'Available' : 'Unavailable'} · Opening: {timeValue(meal.openingTime, '00:00')} · Closing: {timeValue(meal.closingTime, '23:59')}</Typography><Stack direction="row" spacing={1} mt={2}><AppButton size="small" onClick={() => edit(meal)}>Edit</AppButton><AppButton color="secondary" size="small" onClick={() => remove(meal._id)}>Remove</AppButton></Stack></AppCard></Grid>)}</Grid></Grid>
    <Grid size={{ xs: 12 }}><AppCard><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={2} mb={2}><Box><Typography variant="h6" fontWeight={800}>Menu history</Typography><Typography variant="body2" color="text.secondary">Select and delete past menu records only.</Typography></Box><Stack direction="row" spacing={1}><TextField label="Menu date" type="date" value={historyDate} onChange={(event) => { setHistoryDate(event.target.value); setSelectedHistoryIds([]); }} slotProps={{ inputLabel: { shrink: true } }} size="small" /><AppButton size="small" variant="outlined" onClick={() => { setHistoryDate(''); setSelectedHistoryIds([]); }}>All dates</AppButton><AppButton size="small" color="secondary" disabled={!selectedHistoryIds.length || deleting} onClick={deleteSelected}>{deleting ? 'Deleting...' : `Delete Selected (${selectedHistoryIds.length})`}</AppButton></Stack></Stack><AppTable columns={[{ key: 'select', label: 'Select' }, { key: 'date', label: 'Meal date' }, { key: 'type', label: 'Meal type' }, { key: 'category', label: 'Category' }, { key: 'food', label: 'Food' }, { key: 'price', label: 'Price' }, { key: 'availability', label: 'Availability' }, { key: 'added', label: 'Added on' }]} rows={pastHistory.map((meal) => ({ id: meal._id, select: <Checkbox size="small" checked={selectedHistoryIds.includes(meal._id)} onChange={() => toggleHistory(meal._id)} inputProps={{ 'aria-label': `Select ${meal.foodName}` }} />, date: new Date(meal.date).toLocaleDateString(), type: meal.mealType, category: categoryLabel(meal), food: meal.foodName, price: `Rs. ${Number(meal.price || 0).toFixed(2)}`, availability: meal.isAvailable ? 'Available' : 'Unavailable', added: new Date(meal.createdAt).toLocaleString() }))} />{!pastHistory.length && <Typography color="text.secondary" textAlign="center" py={3}>No past menu records found.</Typography>}</AppCard></Grid>
  </Grid></>;
}
export default MenuManagementPage;
